#!/usr/bin/env node
/**
 * dsh-rewind build — produces the npm-package artifacts under lib/:
 *   lib/index.js  — host half: src/index.ts bundled to plain ESM. Every
 *                   `@deepseek-ai/*` import stays external: the dsh loader
 *                   resolves those from the harness installation, never from
 *                   this package.
 *   lib/client.js — client half: src/client/index.ts bundled to CJS, then
 *                   wrapped in the web boot handoff
 *                   `window.__ModuleLoader__.load({ id, factory })`, the
 *                   closure-factory format every `dsh.client` package's
 *                   `./client` export must use. The client half is plain DOM
 *                   plus a React portal bridge: `react`, `react-dom` and
 *                   `react/jsx-runtime` stay external so the injected
 *                   `require` resolves them from the harness web profile's
 *                   module graph (the profile ships React 18).
 *
 * Type checking is a separate step (`npm run typecheck`, tsc --noEmit); this
 * script only transpiles (esbuild) and runs smoke checks: both outputs must
 * parse, and the host half must import with the expected plugin shape.
 */
import { build } from 'esbuild'
import { execSync } from 'node:child_process'
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(await readFile(join(ROOT, 'package.json'), 'utf8'))

// Clean first: stale declarations from earlier builds (e.g. a removed module's
// `ledger.d.ts`) must not survive into the next tarball.
await rm(join(ROOT, 'lib'), { recursive: true, force: true })
await mkdir(join(ROOT, 'lib'), { recursive: true })

// ---- type declarations: host (lib/types) + client (lib/types/client) ----
execSync('npx tsc -p tsconfig.build.json', { cwd: ROOT, stdio: 'inherit' })
execSync('npx tsc -p tsconfig.client.json', { cwd: ROOT, stdio: 'inherit' })

// ---- host half: bundled TS -> ESM (@deepseek-ai/* stays external) ----
await build({
  entryPoints: [join(ROOT, 'src', 'index.ts')],
  outfile: join(ROOT, 'lib', 'index.js'),
  format: 'esm',
  platform: 'node',
  target: 'es2024',
  bundle: true,
  external: ['@deepseek-ai/*'],
  sourcemap: false,
})

// ---- client half: bundled TS/TSX -> CJS, then wrapped in the loader handoff ----
await build({
  entryPoints: [join(ROOT, 'src', 'client', 'index.ts')],
  outfile: join(ROOT, 'lib', '_client.js'),
  format: 'cjs',
  platform: 'browser',
  target: 'es2020',
  bundle: true,
  // React stays external: the web profile's module loader resolves these
  // from the harness installation (the profile ships react@18).
  external: ['react', 'react-dom', 'react/jsx-runtime'],
  jsx: 'automatic',
  sourcemap: false,
})
const clientSource = await readFile(join(ROOT, 'lib', '_client.js'), 'utf8')
await rm(join(ROOT, 'lib', '_client.js'))

const bundle = [
  '/* dsh-rewind client bundle — generated by scripts/build.mjs from src/client/ */',
  'window.__ModuleLoader__.load({',
  `  id: ${JSON.stringify(pkg.name)},`,
  '  factory: (require) => {',
  '    var module = { exports: {} };',
  '    var exports = module.exports;',
  clientSource.replace(/\s+$/, '\n'),
  '    return module.exports;',
  '  }',
  '});',
  '',
].join('\n')
await writeFile(join(ROOT, 'lib', 'client.js'), bundle)

// ---- smoke checks ----
const host = await readFile(join(ROOT, 'lib', 'index.js'), 'utf8')
const exportBlock = host.slice(host.lastIndexOf('export {'))
for (const needle of ['name', 'inject', 'apply']) {
  if (!exportBlock.includes(needle)) throw new Error(`host bundle missing export ${needle}`)
}
for (const needle of ['window.__ModuleLoader__.load', `id: ${JSON.stringify(pkg.name)}`]) {
  if (!bundle.includes(needle)) throw new Error(`client bundle missing ${needle}`)
}
// Declarations must exist (published tarball carries them).
for (const dts of ['lib/types/index.d.ts', 'lib/types/client/index.d.ts']) {
  await readFile(join(ROOT, dts), 'utf8')
}
console.log('build ok: lib/index.js (host), lib/client.js (client), lib/types/ (declarations)')
